/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universitaet;

import com.majdtalji.universitaet.db.ConnectionDataBase;
import com.majdtalji.universitaet.hilfe.ChangeStyle;
import com.majdtalji.universitaet.hilfe.UeberUns;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.ImageIcon;

/**
 *
 * @author Majd
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    final Font font;

    public static String id = "";
    public static String user = "";

    Connection con = null;
    PreparedStatement com = null;
    ResultSet rst = null;

    public Login() {
        initComponents();
        //           RIGHT_TO_LEFT
        //this.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        //jMenuBar1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        font = jCheckBox1.getFont();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        idOrName = new javax.swing.JTextField();
        passLabel = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        selectPersonLabel = new javax.swing.JLabel();
        selectPerson = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        loginB = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        loginA = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        h1 = new javax.swing.JMenu();
        changeStyle = new javax.swing.JMenu();
        s1 = new javax.swing.JMenuItem();
        s2 = new javax.swing.JMenuItem();
        s3 = new javax.swing.JMenuItem();
        s4 = new javax.swing.JMenuItem();
        s5 = new javax.swing.JMenuItem();
        s6 = new javax.swing.JMenuItem();
        s7 = new javax.swing.JMenuItem();
        s8 = new javax.swing.JMenuItem();
        s9 = new javax.swing.JMenuItem();
        s10 = new javax.swing.JMenuItem();
        s11 = new javax.swing.JMenuItem();
        s12 = new javax.swing.JMenuItem();
        s13 = new javax.swing.JMenuItem();
        s14 = new javax.swing.JMenuItem();
        help = new javax.swing.JMenuItem();
        my = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Einloggen");
        setIconImage(new ImageIcon(getClass().getResource("/image/icon-hochschule.png")).getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(695, 346));

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 255), new java.awt.Color(102, 51, 255)));
        jPanel2.setPreferredSize(new java.awt.Dimension(616, 231));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login2.jpeg"))); // NOI18N

        idLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        idLabel.setForeground(new java.awt.Color(0, 255, 204));
        idLabel.setText("ID Nummer");

        idOrName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        passLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        passLabel.setForeground(new java.awt.Color(0, 255, 204));
        passLabel.setText("Passwort");

        pass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        selectPersonLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        selectPersonLabel.setForeground(new java.awt.Color(0, 255, 204));
        selectPersonLabel.setText("Wählen Person");

        selectPerson.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        selectPerson.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Verwaltung", "Doktor", "Student" }));
        selectPerson.setSelectedIndex(-1);
        selectPerson.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectPersonItemStateChanged(evt);
            }
        });

        jCheckBox1.setBackground(new java.awt.Color(0, 0, 255));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Passwort anzeigen");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        loginB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginB.setText("Einloggen >>");
        loginB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Beenden");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(loginB)
                        .addGap(31, 31, 31)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(51, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passLabel)
                            .addComponent(idLabel)
                            .addComponent(selectPersonLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(idOrName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(selectPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idLabel)
                            .addComponent(idOrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passLabel)
                            .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox1)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectPersonLabel)
                            .addComponent(selectPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loginB)
                            .addComponent(jButton4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Anmeldefenster");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        file.setText("Datei");
        file.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        loginA.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        loginA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loginA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login.png"))); // NOI18N
        loginA.setText("Eingang");
        loginA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginAActionPerformed(evt);
            }
        });
        file.add(loginA);

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        exit.setText("Ausgang");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        file.add(exit);

        jMenuBar1.add(file);

        h1.setText("Hilfe");
        h1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        changeStyle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/style.jpeg"))); // NOI18N
        changeStyle.setText("Style");

        s1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s1.setText("Style 1");
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });
        changeStyle.add(s1);

        s2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s2.setText("Style 2");
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });
        changeStyle.add(s2);

        s3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s3.setText("Style 3");
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });
        changeStyle.add(s3);

        s4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s4.setText("Style 4");
        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });
        changeStyle.add(s4);

        s5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s5.setText("Style 5");
        s5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s5ActionPerformed(evt);
            }
        });
        changeStyle.add(s5);

        s6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s6.setText("Style 6");
        s6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s6ActionPerformed(evt);
            }
        });
        changeStyle.add(s6);

        s7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s7.setText("Style 7");
        s7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s7ActionPerformed(evt);
            }
        });
        changeStyle.add(s7);

        s8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s8.setText("Style 8");
        s8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s8ActionPerformed(evt);
            }
        });
        changeStyle.add(s8);

        s9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s9.setText("Style 9");
        s9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s9ActionPerformed(evt);
            }
        });
        changeStyle.add(s9);

        s10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s10.setText("Style 10");
        s10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s10ActionPerformed(evt);
            }
        });
        changeStyle.add(s10);

        s11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s11.setText("Style 11");
        s11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s11ActionPerformed(evt);
            }
        });
        changeStyle.add(s11);

        s12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s12.setText("Style 12");
        s12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s12ActionPerformed(evt);
            }
        });
        changeStyle.add(s12);

        s13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s13.setText("Style 13");
        s13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s13ActionPerformed(evt);
            }
        });
        changeStyle.add(s13);

        s14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s14.setText("Betriebssystem");
        s14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s14ActionPerformed(evt);
            }
        });
        changeStyle.add(s14);

        h1.add(changeStyle);

        help.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        help.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/help.png"))); // NOI18N
        help.setText("Hilfe");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        h1.add(help);

        my.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        my.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        my.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/about.png"))); // NOI18N
        my.setText("Über");
        my.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myActionPerformed(evt);
            }
        });
        h1.add(my);

        jMenuBar1.add(h1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(702, 380));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginAActionPerformed

        loginBActionPerformed(evt);

    }//GEN-LAST:event_loginAActionPerformed

    private void loginBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBActionPerformed

        String miss = "Sie haben vergessen, die folgenden Daten einzugeben :\n";
        if (idOrName.getText().equals("")) {
            miss += idLabel.getText() + "\n";
        }
        if (pass.getText().equals("")) {
            miss += passLabel.getText() + "\n";
        }
        if (selectPerson.getSelectedIndex() == -1) {
            miss += selectPersonLabel.getText() + "\n";
        }
        if (!idOrName.getText().equals("") && !pass.getText().equals("") && selectPerson.getSelectedIndex() != -1) {

            if (selectPerson.getSelectedIndex() == 0) {
                adminLogin();
            } else if (selectPerson.getSelectedIndex() == 1) {
                if (!isDigit(idOrName.getText())) {
                    JOptionPane.showMessageDialog(null, "Bitte geben Sie nicht die Text-ID ein.", "Datenverlust", 2);
                } else {
                    doctorLogin();
                }
            } else if (selectPerson.getSelectedIndex() == 2) {
                if (!isDigit(idOrName.getText())) {
                    JOptionPane.showMessageDialog(null, "Bitte geben Sie nicht die Text-ID ein.", "Datenverlust", 2);
                } else {
                    studentLogin();
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, miss, "Datenverlust", 2);
        }

    }//GEN-LAST:event_loginBActionPerformed

    public static boolean isDigit(String... text) {
        for (String s : text) {
            if (!s.matches("[0-9]+")) {
                return false;
            }
        }
        return true;
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed


    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed

        if (jCheckBox1.isSelected()) {
            pass.setEchoChar((char) 0);
        } else {
            pass.setEchoChar('\u25cf');
            pass.setFont(font);
        }

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void myActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myActionPerformed

        new UeberUns().setVisible(true);

    }//GEN-LAST:event_myActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        JOptionPane.showMessageDialog(null, "Entschuldigung, Es ist momenten inaktiv!");
    }//GEN-LAST:event_helpActionPerformed

    private void selectPersonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectPersonItemStateChanged

        if (selectPerson.getSelectedIndex() == 0) {
            idLabel.setText("Benutzername");
        } else if (selectPerson.getSelectedIndex() == 1 || selectPerson.getSelectedIndex() == 2) {
            idLabel.setText("ID Nummer");
        }

    }//GEN-LAST:event_selectPersonItemStateChanged

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        new ChangeStyle().lookAndFeel(0);

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s1ActionPerformed

    private void s13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s13ActionPerformed
        new ChangeStyle().lookAndFeel(12);

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s13ActionPerformed

    private void s14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s14ActionPerformed
        new ChangeStyle().lookAndFeel();

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s14ActionPerformed

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        new ChangeStyle().lookAndFeel(1);

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s2ActionPerformed

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
        new ChangeStyle().lookAndFeel(2);

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s3ActionPerformed

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed
        new ChangeStyle().lookAndFeel(3);

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s4ActionPerformed

    private void s5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s5ActionPerformed
        new ChangeStyle().lookAndFeel(4);

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s5ActionPerformed

    private void s6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s6ActionPerformed
        new ChangeStyle().lookAndFeel(5);

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s6ActionPerformed

    private void s12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s12ActionPerformed
        new ChangeStyle().lookAndFeel(11);

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s12ActionPerformed

    private void s11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s11ActionPerformed
        new ChangeStyle().lookAndFeel(10);

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s11ActionPerformed

    private void s10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s10ActionPerformed
        new ChangeStyle().lookAndFeel(9);

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s10ActionPerformed

    private void s9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s9ActionPerformed
        new ChangeStyle().lookAndFeel(8);

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s9ActionPerformed

    private void s8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s8ActionPerformed
        new ChangeStyle().lookAndFeel(7);

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s8ActionPerformed

    private void s7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s7ActionPerformed
        new ChangeStyle().lookAndFeel(6);

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu changeStyle;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu file;
    private javax.swing.JMenu h1;
    private javax.swing.JMenuItem help;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idOrName;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem loginA;
    private javax.swing.JButton loginB;
    private javax.swing.JMenuItem my;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel passLabel;
    private javax.swing.JMenuItem s1;
    private javax.swing.JMenuItem s10;
    private javax.swing.JMenuItem s11;
    private javax.swing.JMenuItem s12;
    private javax.swing.JMenuItem s13;
    private javax.swing.JMenuItem s14;
    private javax.swing.JMenuItem s2;
    private javax.swing.JMenuItem s3;
    private javax.swing.JMenuItem s4;
    private javax.swing.JMenuItem s5;
    private javax.swing.JMenuItem s6;
    private javax.swing.JMenuItem s7;
    private javax.swing.JMenuItem s8;
    private javax.swing.JMenuItem s9;
    private javax.swing.JComboBox<String> selectPerson;
    private javax.swing.JLabel selectPersonLabel;
    // End of variables declaration//GEN-END:variables

    private void adminLogin() {

        user = idOrName.getText().trim();
        String password = pass.getText().trim();
        if (user.equals("admin") && password.equals("123456")) {
            MainMenu mainMenu = new MainMenu();
            mainMenu.d.setEnabled(false);
            mainMenu.s.setEnabled(false);
            mainMenu.setVisible(true);
            this.setVisible(false);
            JOptionPane.showMessageDialog(null, "Willkommen, " + user);
        } else {
            JOptionPane.showMessageDialog(null, "Überprüfen Sie die Gültigkeit der eingegebenen Daten!", "Die Informationen sind falsch", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void doctorLogin() {
        //id_doctor+name_doctor+password+mobile+address+gender
        id = idOrName.getText().trim();
        String password = pass.getText().trim();

        try {
            con = ConnectionDataBase.getConnection();
            com = con.prepareStatement("SELECT * FROM doctor WHERE id_doctor = '" + Integer.parseInt(id) + "' AND password = '" + password + "'");
            rst = com.executeQuery();

            if (rst.next()) {
                user = rst.getString("name_doctor");
                MainMenu mainMenu = new MainMenu();
                mainMenu.a.setEnabled(false);
                mainMenu.s.setEnabled(false);
                mainMenu.setVisible(true);
                this.setVisible(false);
                JOptionPane.showMessageDialog(null, "Willkommen, Dr." + user);
            } else {
                JOptionPane.showMessageDialog(null, "Überprüfen Sie die Gültigkeit der eingegebenen Daten!", "Die Informationen sind falsch", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
        } finally {
            try {
                con.close();
            } catch (Exception ex) {
            }
        }

    }

    private void studentLogin() {
//        	id_student+name_student+password+mobile+gender+avg+required_amount+amount_paid+rest_of_the_fees
        id = idOrName.getText().trim();
        String password = pass.getText().trim();

        try {
            con = ConnectionDataBase.getConnection();
            com = con.prepareStatement("SELECT * FROM student WHERE id_student = '" + Integer.parseInt(id) + "' AND password = '" + password + "'");
            rst = com.executeQuery();

            if (rst.next()) {
                user = rst.getString("name_student");
                MainMenu mainMenu = new MainMenu();
                mainMenu.a.setEnabled(false);
                mainMenu.d.setEnabled(false);
                mainMenu.setVisible(true);
                this.setVisible(false);
                JOptionPane.showMessageDialog(null, "Willkommen, " + user);
            } else {
                JOptionPane.showMessageDialog(null, "Überprüfen Sie die Gültigkeit der eingegebenen Daten!", "Die Informationen sind falsch", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
        } finally {
            try {
                con.close();
                rst.close();
            } catch (Exception ex) {
            }
        }
    }

}
