/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universitaet;

import com.majdtalji.universitaet.student.Avarge;
import com.majdtalji.universitaet.student.KashfMark;
import com.majdtalji.universitaet.student.ResCourse;
import com.majdtalji.universitaet.doctor.AddMarkStudent;
import com.majdtalji.universitaet.doctor.DisplayAllStudent;
import com.majdtalji.universitaet.db.ConnectionDataBase;
import com.majdtalji.universitaet.verwaltung.ResDelCourse;
import com.majdtalji.universitaet.verwaltung.TsdedRsom;
import com.majdtalji.universitaet.verwaltung.SelectSemester;
import com.majdtalji.universitaet.doctor.ProfileDoctor;
import com.majdtalji.universitaet.student.ProfilePersonaly;
import com.majdtalji.universitaet.verwaltung.Doctor;
import com.majdtalji.universitaet.verwaltung.Course;
import com.majdtalji.universitaet.gemeinsamerstudentunddoctor.ChangePassword;
import com.majdtalji.universitaet.hilfe.ChangeStyle;
import com.majdtalji.universitaet.verwaltung.Student;
import com.majdtalji.universitaet.hilfe.UeberUns;
import com.majdtalji.universitaet.verwaltung.AnzeigenDoktoren;
import com.majdtalji.universitaet.verwaltung.AnzeigenKurse;
import com.majdtalji.universitaet.verwaltung.AnzeigenStudenten;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.ImageIcon;

/**
 *
 * @author Majd
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public static int ch = 1;
    public static String changePasswordSD = "student";
    public static int semester = 1;

    public MainMenu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        //jMenuBar1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        selectSemester();
    }

    private void selectSemester() {

        Connection con = null;
        PreparedStatement com = null;
        ResultSet rst = null;

        try {
            con = ConnectionDataBase.getConnection();
            com = con.prepareStatement("SELECT * FROM semester");
            rst = com.executeQuery();

            rst.next();
            if (Integer.parseInt(rst.getString("first")) == 1) {
                semester = 1;
            } else {
                semester = 2;
            }

        } catch (Exception e) {
        } finally {
            try {
                com.close();
                con.close();
                rst.close();
            } catch (Exception ex) {
            }
        }

    }

    /*
    @Override
    public void paint(Graphics g) {
            
        try {
            BufferedImage loadedpic = ImageIO.read(this.getClass().getResource("image\\a123.jpg"));
            g.drawImage(loadedpic, 0, 0, getWidth(), getHeight(), this);
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }

    }
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        a = new javax.swing.JMenu();
        student = new javax.swing.JMenu();
        addS = new javax.swing.JMenuItem();
        updateS = new javax.swing.JMenuItem();
        deleteS = new javax.swing.JMenuItem();
        anzeigenStudenten = new javax.swing.JMenuItem();
        doctor = new javax.swing.JMenu();
        addD = new javax.swing.JMenuItem();
        updateD = new javax.swing.JMenuItem();
        deleteD = new javax.swing.JMenuItem();
        anzeigenDoktoren = new javax.swing.JMenuItem();
        course = new javax.swing.JMenu();
        addC = new javax.swing.JMenuItem();
        updateC = new javax.swing.JMenuItem();
        deleteC = new javax.swing.JMenuItem();
        anzeigenKurse = new javax.swing.JMenuItem();
        selectSemester = new javax.swing.JMenuItem();
        tsdedFees = new javax.swing.JMenuItem();
        addOrRemoveCourse = new javax.swing.JMenuItem();
        d = new javax.swing.JMenu();
        filePersonD = new javax.swing.JMenuItem();
        displayStudent = new javax.swing.JMenuItem();
        addMark = new javax.swing.JMenuItem();
        changePasswordD = new javax.swing.JMenuItem();
        s = new javax.swing.JMenu();
        filePersonS = new javax.swing.JMenuItem();
        RegisterCourse = new javax.swing.JMenuItem();
        markS = new javax.swing.JMenuItem();
        avg = new javax.swing.JMenuItem();
        changePassS = new javax.swing.JMenuItem();
        h = new javax.swing.JMenu();
        changeStyle = new javax.swing.JMenu();
        s1 = new javax.swing.JMenuItem();
        s2 = new javax.swing.JMenuItem();
        s3 = new javax.swing.JMenuItem();
        s4 = new javax.swing.JMenuItem();
        s5 = new javax.swing.JMenuItem();
        s6 = new javax.swing.JMenuItem();
        s7 = new javax.swing.JMenuItem();
        s8 = new javax.swing.JMenuItem();
        s9 = new javax.swing.JMenuItem();
        s10 = new javax.swing.JMenuItem();
        s11 = new javax.swing.JMenuItem();
        s12 = new javax.swing.JMenuItem();
        s13 = new javax.swing.JMenuItem();
        s14 = new javax.swing.JMenuItem();
        help = new javax.swing.JMenuItem();
        my = new javax.swing.JMenuItem();
        l = new javax.swing.JMenu();
        logOff = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/image/icon-hochschule.png")).getImage());
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dusk-at-st-lous.hell.jpg"))); // NOI18N

        a.setText("Verwaltung");
        a.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        student.setText("Student");
        student.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        addS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add-user-icon.png"))); // NOI18N
        addS.setText("Student hinzufügen");
        addS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSActionPerformed(evt);
            }
        });
        student.add(addS);

        updateS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit-validated-icon.png"))); // NOI18N
        updateS.setText("Student bearbeiten");
        updateS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSActionPerformed(evt);
            }
        });
        student.add(updateS);

        deleteS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/deleteuser.png"))); // NOI18N
        deleteS.setText("Student löschen");
        deleteS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSActionPerformed(evt);
            }
        });
        student.add(deleteS);

        anzeigenStudenten.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        anzeigenStudenten.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/table_header.png"))); // NOI18N
        anzeigenStudenten.setText("Studenten anzeigen");
        anzeigenStudenten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anzeigenStudentenActionPerformed(evt);
            }
        });
        student.add(anzeigenStudenten);

        a.add(student);

        doctor.setText("Doktor");
        doctor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        addD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add-user-icon.png"))); // NOI18N
        addD.setText("Doktor hinzufügen");
        addD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDActionPerformed(evt);
            }
        });
        doctor.add(addD);

        updateD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit-validated-icon.png"))); // NOI18N
        updateD.setText("Doktor bearbeiten");
        updateD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDActionPerformed(evt);
            }
        });
        doctor.add(updateD);

        deleteD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/deleteuser.png"))); // NOI18N
        deleteD.setText("Doktor löschen");
        deleteD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDActionPerformed(evt);
            }
        });
        doctor.add(deleteD);

        anzeigenDoktoren.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        anzeigenDoktoren.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/table_header.png"))); // NOI18N
        anzeigenDoktoren.setText("Doktoren anzeigen");
        anzeigenDoktoren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anzeigenDoktorenActionPerformed(evt);
            }
        });
        doctor.add(anzeigenDoktoren);

        a.add(doctor);

        course.setText("Kurs");
        course.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        addC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add-user-icon.png"))); // NOI18N
        addC.setText("Kurs hinzufügen");
        addC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCActionPerformed(evt);
            }
        });
        course.add(addC);

        updateC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit-validated-icon.png"))); // NOI18N
        updateC.setText("Kurs bearbeiten");
        updateC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCActionPerformed(evt);
            }
        });
        course.add(updateC);

        deleteC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/deleteuser.png"))); // NOI18N
        deleteC.setText("Kurs löschen");
        deleteC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCActionPerformed(evt);
            }
        });
        course.add(deleteC);

        anzeigenKurse.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        anzeigenKurse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/table_header.png"))); // NOI18N
        anzeigenKurse.setText("Kurse anzeigen");
        anzeigenKurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anzeigenKurseActionPerformed(evt);
            }
        });
        course.add(anzeigenKurse);

        a.add(course);

        selectSemester.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectSemester.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/001_39.png"))); // NOI18N
        selectSemester.setText("Semester auswählen");
        selectSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectSemesterActionPerformed(evt);
            }
        });
        a.add(selectSemester);

        tsdedFees.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tsdedFees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/euro-3717536_960_720.png"))); // NOI18N
        tsdedFees.setText("Zahlung gebühren");
        tsdedFees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsdedFeesActionPerformed(evt);
            }
        });
        a.add(tsdedFees);

        addOrRemoveCourse.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addOrRemoveCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus-minus.png"))); // NOI18N
        addOrRemoveCourse.setText("Kurs Student hinzufügen oder löschen");
        addOrRemoveCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrRemoveCourseActionPerformed(evt);
            }
        });
        a.add(addOrRemoveCourse);

        jMenuBar1.add(a);

        d.setText("Doctor");
        d.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        filePersonD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        filePersonD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profile-icon-28.png"))); // NOI18N
        filePersonD.setText("Profil ansehen");
        filePersonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filePersonDActionPerformed(evt);
            }
        });
        d.add(filePersonD);

        displayStudent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        displayStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/table_header.png"))); // NOI18N
        displayStudent.setText("Studenten in Kurs eingeschreiben");
        displayStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayStudentActionPerformed(evt);
            }
        });
        d.add(displayStudent);

        addMark.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addMark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus-297823_960_720.png"))); // NOI18N
        addMark.setText("Punkte hinzufügen");
        addMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMarkActionPerformed(evt);
            }
        });
        d.add(addMark);

        changePasswordD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        changePasswordD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lock.jpeg"))); // NOI18N
        changePasswordD.setText("Passwort ändern");
        changePasswordD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordDActionPerformed(evt);
            }
        });
        d.add(changePasswordD);

        jMenuBar1.add(d);

        s.setText("Student");
        s.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        filePersonS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        filePersonS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profile-icon-28.png"))); // NOI18N
        filePersonS.setText("Profil ansehen");
        filePersonS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filePersonSActionPerformed(evt);
            }
        });
        s.add(filePersonS);

        RegisterCourse.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RegisterCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus-297823_960_720.png"))); // NOI18N
        RegisterCourse.setText("Kurs anmelden");
        RegisterCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterCourseActionPerformed(evt);
            }
        });
        s.add(RegisterCourse);

        markS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        markS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/JD-02-512.png"))); // NOI18N
        markS.setText("Punkte erkennen");
        markS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markSActionPerformed(evt);
            }
        });
        s.add(markS);

        avg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        avg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/binnary-tree-icon-simple-style-vector-19501083.jpg"))); // NOI18N
        avg.setText("Kumulierte GPA");
        avg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgActionPerformed(evt);
            }
        });
        s.add(avg);

        changePassS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        changePassS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lock.jpeg"))); // NOI18N
        changePassS.setText("Passwort ändern");
        changePassS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassSActionPerformed(evt);
            }
        });
        s.add(changePassS);

        jMenuBar1.add(s);

        h.setText("Assistent");
        h.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        changeStyle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/style.jpeg"))); // NOI18N
        changeStyle.setText("Style");

        s1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s1.setText("Style 1");
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });
        changeStyle.add(s1);

        s2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s2.setText("Style 2");
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });
        changeStyle.add(s2);

        s3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s3.setText("Style 3");
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });
        changeStyle.add(s3);

        s4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s4.setText("Style 4");
        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });
        changeStyle.add(s4);

        s5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s5.setText("Style 5");
        s5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s5ActionPerformed(evt);
            }
        });
        changeStyle.add(s5);

        s6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s6.setText("Style 6");
        s6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s6ActionPerformed(evt);
            }
        });
        changeStyle.add(s6);

        s7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s7.setText("Style 7");
        s7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s7ActionPerformed(evt);
            }
        });
        changeStyle.add(s7);

        s8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s8.setText("Style 8");
        s8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s8ActionPerformed(evt);
            }
        });
        changeStyle.add(s8);

        s9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s9.setText("Style 9");
        s9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s9ActionPerformed(evt);
            }
        });
        changeStyle.add(s9);

        s10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s10.setText("Style 10");
        s10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s10ActionPerformed(evt);
            }
        });
        changeStyle.add(s10);

        s11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s11.setText("Style 11");
        s11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s11ActionPerformed(evt);
            }
        });
        changeStyle.add(s11);

        s12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s12.setText("Style 12");
        s12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s12ActionPerformed(evt);
            }
        });
        changeStyle.add(s12);

        s13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s13.setText("Style 13");
        s13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s13ActionPerformed(evt);
            }
        });
        changeStyle.add(s13);

        s14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s14.setText("Betriebssystem");
        s14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s14ActionPerformed(evt);
            }
        });
        changeStyle.add(s14);

        h.add(changeStyle);

        help.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        help.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/help.png"))); // NOI18N
        help.setText("Hilfe");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        h.add(help);

        my.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        my.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        my.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/about.png"))); // NOI18N
        my.setText("Über");
        my.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myActionPerformed(evt);
            }
        });
        h.add(my);

        jMenuBar1.add(h);

        l.setText("Ausloggen");
        l.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        logOff.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/log off.png"))); // NOI18N
        logOff.setText("Ausloggen");
        logOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOffActionPerformed(evt);
            }
        });
        l.add(logOff);

        jMenuBar1.add(l);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(651, 475));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSActionPerformed

        ch = 3;
        Student s = new Student();
        s.setVisible(true);

    }//GEN-LAST:event_deleteSActionPerformed

    private void addOrRemoveCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrRemoveCourseActionPerformed
        new ResDelCourse().setVisible(true);
    }//GEN-LAST:event_addOrRemoveCourseActionPerformed

    private void selectSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSemesterActionPerformed
        new SelectSemester().setVisible(true);
    }//GEN-LAST:event_selectSemesterActionPerformed

    private void myActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myActionPerformed
        new UeberUns().setVisible(true);
    }//GEN-LAST:event_myActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        JOptionPane.showMessageDialog(null, "Entschuldigung, Es ist momenten inaktiv!");
    }//GEN-LAST:event_helpActionPerformed

    private void logOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOffActionPerformed
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_logOffActionPerformed

    private void addSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSActionPerformed

        ch = 1;
        Student s = new Student();
        s.setVisible(true);

    }//GEN-LAST:event_addSActionPerformed

    private void updateSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSActionPerformed

        ch = 2;
        Student s = new Student();
        s.setVisible(true);

    }//GEN-LAST:event_updateSActionPerformed

    private void changePassSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassSActionPerformed

        changePasswordSD = "student";
        new ChangePassword().setVisible(true);

    }//GEN-LAST:event_changePassSActionPerformed

    private void changePasswordDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordDActionPerformed

        changePasswordSD = "doctor";
        new ChangePassword().setVisible(true);

    }//GEN-LAST:event_changePasswordDActionPerformed

    private void addCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCActionPerformed

        ch = 1;
        new Course().setVisible(true);

    }//GEN-LAST:event_addCActionPerformed

    private void updateCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCActionPerformed

        ch = 2;
        new Course().setVisible(true);

    }//GEN-LAST:event_updateCActionPerformed

    private void deleteCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCActionPerformed

        ch = 3;
        new Course().setVisible(true);

    }//GEN-LAST:event_deleteCActionPerformed

    private void addDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDActionPerformed
        ch = 1;
        new Doctor().setVisible(true);
    }//GEN-LAST:event_addDActionPerformed

    private void updateDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDActionPerformed
        ch = 2;
        new Doctor().setVisible(true);
    }//GEN-LAST:event_updateDActionPerformed

    private void deleteDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDActionPerformed
        ch = 3;
        new Doctor().setVisible(true);
    }//GEN-LAST:event_deleteDActionPerformed

    private void filePersonSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filePersonSActionPerformed
        new ProfilePersonaly().setVisible(true);
    }//GEN-LAST:event_filePersonSActionPerformed

    private void filePersonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filePersonDActionPerformed
        new ProfileDoctor().setVisible(true);
    }//GEN-LAST:event_filePersonDActionPerformed

    private void tsdedFeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsdedFeesActionPerformed
        new TsdedRsom().setVisible(true);
    }//GEN-LAST:event_tsdedFeesActionPerformed

    private void displayStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayStudentActionPerformed
        new DisplayAllStudent().setVisible(true);
    }//GEN-LAST:event_displayStudentActionPerformed

    private void addMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMarkActionPerformed
        new AddMarkStudent();
    }//GEN-LAST:event_addMarkActionPerformed

    private void RegisterCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterCourseActionPerformed
        new ResCourse().setVisible(true);
    }//GEN-LAST:event_RegisterCourseActionPerformed

    private void markSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markSActionPerformed
        new KashfMark().setVisible(true);
    }//GEN-LAST:event_markSActionPerformed

    private void avgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avgActionPerformed
        new Avarge().setVisible(true);
    }//GEN-LAST:event_avgActionPerformed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        new ChangeStyle().lookAndFeel(0);

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s1ActionPerformed

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        new ChangeStyle().lookAndFeel(1);

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s2ActionPerformed

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
        new ChangeStyle().lookAndFeel(2);

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s3ActionPerformed

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed
        new ChangeStyle().lookAndFeel(3);

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s4ActionPerformed

    private void s5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s5ActionPerformed
        new ChangeStyle().lookAndFeel(4);

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s5ActionPerformed

    private void s6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s6ActionPerformed
        new ChangeStyle().lookAndFeel(5);

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s6ActionPerformed

    private void s7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s7ActionPerformed
        new ChangeStyle().lookAndFeel(6);

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s7ActionPerformed

    private void s8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s8ActionPerformed
        new ChangeStyle().lookAndFeel(7);

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s8ActionPerformed

    private void s9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s9ActionPerformed
        new ChangeStyle().lookAndFeel(8);

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s9ActionPerformed

    private void s10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s10ActionPerformed
        new ChangeStyle().lookAndFeel(9);

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s10ActionPerformed

    private void s11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s11ActionPerformed
        new ChangeStyle().lookAndFeel(10);

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s11ActionPerformed

    private void s12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s12ActionPerformed
        new ChangeStyle().lookAndFeel(11);

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s12ActionPerformed

    private void s13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s13ActionPerformed
        new ChangeStyle().lookAndFeel(12);

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s13ActionPerformed

    private void s14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s14ActionPerformed
        new ChangeStyle().lookAndFeel();

        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_s14ActionPerformed

    private void anzeigenStudentenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anzeigenStudentenActionPerformed
        new AnzeigenStudenten().setVisible(true);
    }//GEN-LAST:event_anzeigenStudentenActionPerformed

    private void anzeigenDoktorenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anzeigenDoktorenActionPerformed
        new AnzeigenDoktoren().setVisible(true);
    }//GEN-LAST:event_anzeigenDoktorenActionPerformed

    private void anzeigenKurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anzeigenKurseActionPerformed
        new AnzeigenKurse().setVisible(true);
    }//GEN-LAST:event_anzeigenKurseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem RegisterCourse;
    public javax.swing.JMenu a;
    private javax.swing.JMenuItem addC;
    private javax.swing.JMenuItem addD;
    private javax.swing.JMenuItem addMark;
    private javax.swing.JMenuItem addOrRemoveCourse;
    private javax.swing.JMenuItem addS;
    private javax.swing.JMenuItem anzeigenDoktoren;
    private javax.swing.JMenuItem anzeigenKurse;
    private javax.swing.JMenuItem anzeigenStudenten;
    private javax.swing.JMenuItem avg;
    private javax.swing.JMenuItem changePassS;
    private javax.swing.JMenuItem changePasswordD;
    private javax.swing.JMenu changeStyle;
    private javax.swing.JMenu course;
    public javax.swing.JMenu d;
    private javax.swing.JMenuItem deleteC;
    private javax.swing.JMenuItem deleteD;
    private javax.swing.JMenuItem deleteS;
    private javax.swing.JMenuItem displayStudent;
    private javax.swing.JMenu doctor;
    private javax.swing.JMenuItem filePersonD;
    private javax.swing.JMenuItem filePersonS;
    private javax.swing.JMenu h;
    private javax.swing.JMenuItem help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu l;
    private javax.swing.JMenuItem logOff;
    private javax.swing.JMenuItem markS;
    private javax.swing.JMenuItem my;
    public javax.swing.JMenu s;
    private javax.swing.JMenuItem s1;
    private javax.swing.JMenuItem s10;
    private javax.swing.JMenuItem s11;
    private javax.swing.JMenuItem s12;
    private javax.swing.JMenuItem s13;
    private javax.swing.JMenuItem s14;
    private javax.swing.JMenuItem s2;
    private javax.swing.JMenuItem s3;
    private javax.swing.JMenuItem s4;
    private javax.swing.JMenuItem s5;
    private javax.swing.JMenuItem s6;
    private javax.swing.JMenuItem s7;
    private javax.swing.JMenuItem s8;
    private javax.swing.JMenuItem s9;
    private javax.swing.JMenuItem selectSemester;
    private javax.swing.JMenu student;
    private javax.swing.JMenuItem tsdedFees;
    private javax.swing.JMenuItem updateC;
    private javax.swing.JMenuItem updateD;
    private javax.swing.JMenuItem updateS;
    // End of variables declaration//GEN-END:variables
}
