/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.majdtalji.universitaet.gemeinsamerstudentunddoctor;

import com.majdtalji.universitaet.db.ConnectionDataBase;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import universitaet.Login;
import universitaet.MainMenu;

/**
 *
 * @author Majd
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form ChangePassword
     */
    Connection con = null;
    PreparedStatement com = null;
    ResultSet rst = null;

    public ChangePassword() {
        initComponents();
        id.setText(Login.id);

        {
            //jLabel6.setVisible(false);
            jLabel6.setForeground(jPanel1.getBackground());
            jLabel7.setForeground(jPanel1.getBackground());
//            jLabel6.setFont(new Font(jLabel6.getName(), Font.BOLD, 12));
        }

        if (MainMenu.changePasswordSD.equals("doctor")) {
            this.setTitle("Ändern Sie das Passwort für den Doctor.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        oldPassLabel = new javax.swing.JLabel();
        newPassLabel = new javax.swing.JLabel();
        cPassLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        oldPass = new javax.swing.JPasswordField();
        newPass = new javax.swing.JPasswordField();
        cPass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ändern Sie das Passwort für den Student.");
        setIconImage(new ImageIcon(getClass().getResource("/image/icon-hochschule.png")).getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Passwort ändern");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(117, 117, 117))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(12, 12, 12))
        );

        idLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(0, 255, 204));
        idLabel.setText("Identnummer");

        id.setEditable(false);
        id.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        oldPassLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        oldPassLabel.setForeground(new java.awt.Color(0, 255, 204));
        oldPassLabel.setText("Altes Passwort");

        newPassLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newPassLabel.setForeground(new java.awt.Color(0, 255, 204));
        newPassLabel.setText("Neues Passwort");

        cPassLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cPassLabel.setForeground(new java.awt.Color(0, 255, 204));
        cPassLabel.setText("Passwort bestätigen");

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Beenden");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 204, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Ändern");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        oldPass.setBackground(new java.awt.Color(240, 240, 240));
        oldPass.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        oldPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                oldPassKeyReleased(evt);
            }
        });

        newPass.setBackground(new java.awt.Color(240, 240, 240));
        newPass.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        newPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                newPassKeyReleased(evt);
            }
        });

        cPass.setBackground(new java.awt.Color(240, 240, 240));
        cPass.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cPassKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("Altes Passwort");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("Sind identisch nicht, bitte ändern");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(idLabel)
                                        .addComponent(oldPassLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(newPassLabel))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                    .addComponent(oldPass)
                                    .addComponent(newPass)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cPassLabel)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(cPass, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldPassLabel)
                    .addComponent(oldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPassLabel)
                    .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel6)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cPassLabel)
                    .addComponent(cPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(463, 342));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void newPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newPassKeyReleased

        oldPassBettwenNewPass();

        confPassBetweenNewPass();

    }//GEN-LAST:event_newPassKeyReleased

    private void cPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cPassKeyReleased

        confPassBetweenNewPass();

    }//GEN-LAST:event_cPassKeyReleased

    private void confPassBetweenNewPass() {
        String newPassword = String.valueOf(newPass.getText());
        String confPassword = String.valueOf(cPass.getText());

        if (!cPass.getText().equals("") && !newPass.getText().equals("")) {
            if (confPassword.equals(newPassword)) {
                jLabel7.setText("Sind identisch");
                jLabel7.setForeground(Color.GREEN);
//                jLabel7.setVisible(true);
            } else {
                jLabel7.setText("Sind identisch nicht, bitte ändern");
                jLabel7.setForeground(Color.red);
//                jLabel7.setVisible(true);
            }
        }
    }

    private void oldPassBettwenNewPass() {
        String oldPassword = String.valueOf(oldPass.getText());
        String newPassword = String.valueOf(newPass.getText());

        if (!oldPass.getText().equals("") && !newPass.getText().equals("")) {
            if (oldPassword.equals(newPassword)) {
//                jLabel6.setText("Altes Passwort");
                jLabel6.setForeground(Color.red);
                jLabel6.setVisible(true);
                cPass.setRequestFocusEnabled(false);
            } else {
//                jLabel6.setText("Altes Passwort");
//                jLabel6.setForeground(Color.black);
                jLabel6.setForeground(jPanel1.getBackground());
//                jLabel6.setVisible(false);
                cPass.setRequestFocusEnabled(true);
            }
        }
    }

    private void oldPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oldPassKeyReleased
        oldPassBettwenNewPass();
    }//GEN-LAST:event_oldPassKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        changePass(MainMenu.changePasswordSD);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void changePass(String nameTable) {

        String miss = "Sie haben vergessen, die folgenden Daten einzugeben :\n";
        if (oldPass.getText().equals("")) {
            miss += oldPassLabel.getText() + "\n";
        }
        if (newPass.getText().equals("")) {
            miss += newPassLabel.getText() + "\n";
        }
        if (cPass.getText().equals("")) {
            miss += cPassLabel.getText() + "\n";
        }
        if (!oldPass.getText().equals("") && !newPass.getText().equals("") && !cPass.getText().equals("")) {
//            id_student + name_student + password + mobile + gender + avg + required_amount + amount_paid + rest_of_the_fees
            //id_doctor+name_doctor+password+mobile+address+gender
            try {
                con = ConnectionDataBase.getConnection();
                com = con.prepareStatement("SELECT password FROM " + nameTable + " WHERE id_" + nameTable + " = '" + Integer.parseInt(id.getText()) + "'");
                rst = com.executeQuery();

                rst.next();
                if (oldPass.getText().equals(rst.getString("password"))) {
                    com = con.prepareStatement("UPDATE " + nameTable + " SET password='" + newPass.getText() + "' WHERE id_" + nameTable + "='" + Integer.parseInt(id.getText()) + "'");
                    com.execute();

                    JOptionPane.showMessageDialog(null, "Passwort wurden erfolgreich geändert.", "Modifiziert", JOptionPane.INFORMATION_MESSAGE);
                    oldPass.setText("");
                    newPass.setText("");
                    cPass.setText("");
                    jLabel6.setForeground(jPanel1.getBackground());
                    jLabel7.setForeground(jPanel1.getBackground());

                } else {
                    JOptionPane.showMessageDialog(null, "Das alte Passwort ist falsch", "Fehler", 2);
                }

            } catch (Exception e) {
            } finally {
                try {
                    con.close();
                    rst.close();
                } catch (Exception ex) {
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, miss, "Datenverlust", 2);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cPass;
    private javax.swing.JLabel cPassLabel;
    private javax.swing.JTextField id;
    private javax.swing.JLabel idLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField newPass;
    private javax.swing.JLabel newPassLabel;
    private javax.swing.JPasswordField oldPass;
    private javax.swing.JLabel oldPassLabel;
    // End of variables declaration//GEN-END:variables
}
