/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.majdtalji.universitaet.student;

import com.majdtalji.universitaet.db.ConnectionDataBase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import universitaet.Login;

/**
 *
 * @author Majd
 */
public class KashfMark extends javax.swing.JFrame {

    /**
     * Creates new form KashfMark
     */
    float countHour = 0;
    float totals = 0;

    Connection con = null;
    PreparedStatement com = null;
    ResultSet rst = null;

    public KashfMark() {
        initComponents();

        id.setText(Login.id);
        name.setText(Login.user);

        marks();
    }

    private void marks() {

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {
//          //            id_student + id_course + name_course + hour + name_doctor + mark1 + mark2
            con = ConnectionDataBase.getConnection();
            com = con.prepareStatement("SELECT * FROM register_student_course WHERE id_student = '" + Integer.parseInt(Login.id) + "'");
            rst = com.executeQuery();

            while (rst.next()) {

                float mark1 = rst.getFloat("mark1");
                float mark2 = rst.getFloat("mark2");
                float total = mark1 + mark2;
                String gr = tagder(total);

                model.addRow(new Object[]{rst.getInt("id_course"), rst.getString("name_course"), rst.getFloat("hour"), mark1, mark2, total, gr});

                float hour = rst.getFloat("hour");
                countHour += hour;
                totals += (total * hour);

            }

            float avg = totals / countHour;
            avgLabel.setText(String.valueOf(avg));
            greateLabel.setText(tagder(avg));

        } catch (Exception e) {
        } finally {
            try {
                con.close();
                rst.close();
            } catch (Exception ex) {
            }
        }

    }

    public static String tagder(float total) {

        if (total >= 90) {
            return "Super";
        } else if (total >= 80) {
            return "Sehr Gut";
        } else if (total >= 70) {
            return "Gut";
        } else if (total >= 60) {
            return "Zulässig";
        } else {
            return "Durchgefallen";
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        oldPassLabel = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        oldPassLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        avgLabel = new javax.swing.JLabel();
        oldPassLabel1 = new javax.swing.JLabel();
        oldPassLabel3 = new javax.swing.JLabel();
        greateLabel = new javax.swing.JLabel();
        druckenTabelle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Punkte erkennen");
        setIconImage(new ImageIcon(getClass().getResource("/image/icon-hochschule.png")).getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        oldPassLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        oldPassLabel.setText("Student Nummer :");

        id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id.setText("-----------------");

        oldPassLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        oldPassLabel2.setText("Student Name :");

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.setText("-----------------");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(oldPassLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(oldPassLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldPassLabel)
                    .addComponent(id)
                    .addComponent(oldPassLabel2)
                    .addComponent(name))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kursnummer", "Kursname", "Anzahl Stunden", "Mittelpunkt", "Endlichpunkt", "Gesamt", "Schätzung"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(5);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(5);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(5);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(5);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(10);
        }

        avgLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        avgLabel.setText("-----------------");

        oldPassLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        oldPassLabel1.setForeground(new java.awt.Color(255, 0, 0));
        oldPassLabel1.setText("Vierteljährlicher Durchschnitt :");

        oldPassLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        oldPassLabel3.setForeground(new java.awt.Color(255, 0, 0));
        oldPassLabel3.setText("Schätzung :");

        greateLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        greateLabel.setText("-----------------");

        druckenTabelle.setBackground(new java.awt.Color(153, 255, 204));
        druckenTabelle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        druckenTabelle.setForeground(new java.awt.Color(0, 153, 153));
        druckenTabelle.setText("Drucken Tabelle");
        druckenTabelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                druckenTabelleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(oldPassLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oldPassLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(greateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(druckenTabelle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldPassLabel1)
                    .addComponent(avgLabel)
                    .addComponent(oldPassLabel3)
                    .addComponent(greateLabel)
                    .addComponent(druckenTabelle))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(740, 441));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void druckenTabelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_druckenTabelleActionPerformed

        try {

            con = ConnectionDataBase.getConnection();

            JasperDesign jd = JRXmlLoader.load("report1.jrxml");

            String sql = "SELECT\n"
                    + "     register_student_course.`name_course` AS register_student_course_name_course,\n"
                    + "     register_student_course.`hour` AS register_student_course_hour,\n"
                    + "     register_student_course.`name_doctor` AS register_student_course_name_doctor,\n"
                    + "     register_student_course.`mark1` AS register_student_course_mark1,\n"
                    + "     register_student_course.`mark2` AS register_student_course_mark2,\n"
                    + "     register_student_course.`id_course` AS register_student_course_id_course\n"
                    + "FROM\n"
                    + "     `register_student_course` register_student_course\n"
                    + " WHERE\n"
                    + "id_student = '" + Integer.parseInt(id.getText()) + "'";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);

            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
            JasperViewer.viewReport(jp, false);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
//            try {
//                jTable1.print();
//            } catch (Exception e) {
//            }
        }

    }//GEN-LAST:event_druckenTabelleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KashfMark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KashfMark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KashfMark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KashfMark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KashfMark().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avgLabel;
    private javax.swing.JButton druckenTabelle;
    private javax.swing.JLabel greateLabel;
    private javax.swing.JLabel id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel oldPassLabel;
    private javax.swing.JLabel oldPassLabel1;
    private javax.swing.JLabel oldPassLabel2;
    private javax.swing.JLabel oldPassLabel3;
    // End of variables declaration//GEN-END:variables
}
