/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.majdtalji.universitaet.student;

import com.majdtalji.universitaet.db.ConnectionDataBase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
import universitaet.Login;
import universitaet.MainMenu;

/**
 *
 * @author Majd
 */
public class ResCourse extends javax.swing.JFrame {

    /**
     * Creates new form ResCourse
     */
    Connection con = null;
    PreparedStatement com = null;
    ResultSet rst = null;

    public ResCourse() {
        initComponents();

        id.setText(Login.id);
        name.setText(Login.user);

        displayCourse();
    }

    private void displayCourse() {

        PreparedStatement com1;
        ResultSet rst1;
        try {
            //              id_student	id_course	name_course	hour	name_doctor	mark1	mark2
            con = ConnectionDataBase.getConnection();
            com = con.prepareStatement("SELECT * FROM course WHERE semester = '" + MainMenu.semester + "'");
            rst = com.executeQuery();

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            while (rst.next()) {

                //              id_student	id_course	name_course	hour	name_doctor	mark1	mark2
                com1 = con.prepareStatement("SELECT * FROM register_student_course WHERE id_student = '" + Login.id + "' and name_course = '" + rst.getString("name_course") + "'");
                rst1 = com1.executeQuery();
                if (rst1.next()) {
                    model.addRow(new Object[]{true, rst.getString("id_course"), rst.getString("name_course"), rst.getFloat("hour"), rst.getString("name_doctor")});
                } else {
                    model.addRow(new Object[]{false, rst.getString("id_course"), rst.getString("name_course"), rst.getFloat("hour"), rst.getString("name_doctor")});

                }

            }

        } catch (Exception e) {
        } finally {
            try {
                con.close();
                rst.close();
            } catch (Exception ex) {
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        oldPassLabel = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        oldPassLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kurs anmelden");
        setIconImage(new ImageIcon(getClass().getResource("/image/icon-hochschule.png")).getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        oldPassLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        oldPassLabel.setText("Student Nummer :");

        id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id.setText("-----------------");

        oldPassLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        oldPassLabel2.setText("Student Name :");

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.setText("-----------------");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(oldPassLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oldPassLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldPassLabel)
                    .addComponent(id)
                    .addComponent(oldPassLabel2)
                    .addComponent(name))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Meldung", "Kursnummer", "Kursname", "Anzahl Stunden", "Kurs Doctor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(15);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(16);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Anmelden");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(610, 374));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //   id_student + id_course + name_course + hour + name_doctor + mark1 + mark2
        try {

            for (int row = 0; row < jTable1.getRowCount(); row++) {
                if (jTable1.getModel().getValueAt(row, 0).equals(true)) {

                    String nameCourse = jTable1.getModel().getValueAt(row, 2).toString();

//                    id_student	id_course	name_course	hour	name_doctor	mark1	mark2
                    con = ConnectionDataBase.getConnection();
                    com = con.prepareStatement("SELECT * FROM register_student_course WHERE id_student = '" + Login.id + "' and name_course = '" + nameCourse + "'");
                    rst = com.executeQuery();

                    int idCourse = Integer.parseInt(jTable1.getModel().getValueAt(row, 1).toString());
                    float hour = Float.parseFloat(jTable1.getModel().getValueAt(row, 3).toString());
                    String nameDoctor = jTable1.getModel().getValueAt(row, 4).toString();

                    if (!rst.next()) {
                        com = con.prepareStatement("INSERT INTO `register_student_course`(`id_student`, `id_course`, `name_course`, `hour`, `name_doctor`, `mark1`, `mark2`) VALUES ('" + Login.id + "','" + idCourse + "','" + nameCourse + "','" + hour + "','" + nameDoctor + "','0','0')");
                        com.execute();

                        {
//                            id_course+name_course+hour+name_doctor+salary_one_hour+semester
                            com = con.prepareStatement("SELECT * FROM course WHERE id_course = '" + idCourse + "'");
                            rst = com.executeQuery();
                            rst.next();
                            float hourCourse = rst.getFloat("hour");
                            float salaryOneHour = rst.getFloat("salary_one_hour");
                            float kostetKurs = hourCourse * salaryOneHour;

//                            id_student+name_student+password+mobile+gender+avg+required_amount+amount_paid+rest_of_the_fees
                            com = con.prepareStatement("SELECT * FROM student WHERE id_student = '" + Login.id + "'");
                            rst = com.executeQuery();
                            rst.next();

                            float amountit = rst.getFloat("required_amount");
                            float restFees = rst.getFloat("rest_of_the_fees");

                            amountit += kostetKurs;
                            restFees += kostetKurs;

                            com = con.prepareStatement("UPDATE student SET required_amount ='" + amountit + "', rest_of_the_fees ='" + restFees + "' WHERE id_student='" + Login.id + "'");
                            com.execute();
                        }
                    }

                }
            }

            JOptionPane.showMessageDialog(null, "Abschluss der Registrierung von Studentenkursen.", "Die Registrierung endet", JOptionPane.INFORMATION_MESSAGE);
            setVisible(false);

        } catch (Exception e) {
            System.out.println(e);
        } finally {
            try {
                con.close();
                rst.close();
            } catch (Exception ex) {
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel oldPassLabel;
    private javax.swing.JLabel oldPassLabel2;
    // End of variables declaration//GEN-END:variables
}
